/**
 * Defaults and limits for video annotation segments.
 */
export const ANNOTATIONS = {
  DEFAULT_SEGMENT_DURATION_MS: 3000,
  MIN_SEGMENT_DURATION_MS: 500,
  DEFAULT_SHAPE_TYPE: 'rectangle',
  DEFAULT_STROKE_COLOR: '#F97316',
  DEFAULT_FILL_COLOR: 'rgba(249, 115, 22, 0.16)',
  DEFAULT_TEXT_COLOR: '#FFF7ED',
  DEFAULT_TEXT: 'Note',
  DEFAULT_FONT_FAMILY: 'sans-serif',
  DEFAULT_FONT_SIZE: 42,
  DEFAULT_FONT_WEIGHT: 700,
  DEFAULT_STROKE_WIDTH: 6,
  DEFAULT_OPACITY: 1,
  MIN_NORMALIZED_SIZE: 0.03,
  MIN_FONT_SIZE: 12,
  MAX_FONT_SIZE: 160,
  MIN_STROKE_WIDTH: 1,
  MAX_STROKE_WIDTH: 24,
  ARROW_HEAD_FACTOR: 3.2,
  ARROW_PADDING_FACTOR: 0.18,
} as const;

export type AnnotationConstants = typeof ANNOTATIONS;
