/**
 * Timing constants for debounce, delays, and animations.
 * Centralizing these prevents magic numbers and enables tuning.
 */

export const TIMING = {
  // Debounce intervals
  RESIZE_DEBOUNCE_MS: 150,
  RESIZE_TRANSITION_LOCK_MS: 200,
  PROJECT_AUTOSAVE_DEBOUNCE_MS: 2000,
  CAPTION_AUTOSAVE_DEBOUNCE_MS: 500,
  PROJECT_AUTOSAVE_ACTIVITY_WINDOW_MS: 10000,
  PROJECT_AUTOSAVE_IDLE_MS: 1500,
  PROJECT_AUTOSAVE_ACTIVITY_CHECK_MS: 500,
  IMAGE_EDITOR_AUTOSAVE_DEBOUNCE_MS: 1000,
  IMAGE_EDITOR_AUTOSAVE_ACTIVITY_WINDOW_MS: 10000,
  IMAGE_EDITOR_AUTOSAVE_IDLE_MS: 1500,
  IMAGE_EDITOR_AUTOSAVE_ACTIVITY_CHECK_MS: 500,

  // Delay for async operations
  RECORDING_COMPLETE_DELAY_MS: 500,
  THUMBNAIL_REFRESH_DELAY_MS: 2000,

  // Tooltip delays
  TOOLTIP_DELAY_MS: 300,

  // UI interaction delays
  SUGGESTION_BLUR_DELAY_MS: 150,

  // Playback behavior
  PLAYBACK_END_RESTART_THRESHOLD_MS: 150,
  SCRUB_PREVIEW_STEP_MS: 16,
  SCRUB_SEEK_STEP_MS: 16,
} as const;

export type TimingConstants = typeof TIMING;
